### ISSUE TITLE
[1.0.4.1] Error: display settings on starting.

### ISSUE THREAD

**Issue by d3nni** [tak-dev/FortniteConfigTool#2]
I get the following error when starting the program, got this for a long time now and just opened that poll now, since there didn't came any new version as I thought.

"Issue displaying current settings
Try loading Fortnite first"

Some things got detected.... like resolution and fullscreen.
But I can see that the fps is always set to 30, even if my settings says they are set to 144 or 160.

Thanks! ;-)

**Comment by tak-dev** [comment]
Thanks for letting me know! It might be incompatible with the update today. I'll take a look a try to get an update released by the end of today.

**Comment by tak-dev** [comment]
@d3nni I checked and it seems to work fine for me. Can you open your config directory (should be a button in the program) and paste/upload the your GameUserSettings.ini file? It sounds like your config file isn't being read properly for whatever reason.

**Comment by d3nni** [comment]
Wow.... didn't thought you will be that fast.

A little better explained... I just got this problem like months, not starting with this update. And I have had many different configs.... from standard to custom. Ofc I can get you mine. 


[GameUserSettings.zip](https://github.com/tak-dev/FortniteConfigTool/files/3731285/GameUserSettings.zip)

**Comment by d3nni** [comment]
Got the problem....

The standard is the follwing, as it is seen in mine config file.... "FrameRateLimit=160.00000"

And it's only checking if I set it to.... "FrameRateLimit=160"

Would be nice if you could fix it. :-)

Thanks! 👍

**Comment by tak-dev** [comment]
GitHub makes it easy :)

I replaced my config with what you just sent me and it [loaded correctly](https://i.imgur.com/lhZ2jMD.png). I thought I handled the issue with the decimal place and zeroes but I'll double check.

**Comment by d3nni** [comment]
> GitHub makes it easy :)
> 
> I replaced my config with what you just sent me and it [loaded correctly](https://i.imgur.com/lhZ2jMD.png). I thought I handled the issue with the decimal place and zeroes but I'll double check.

If I set it to 160 it does also load correctly here, I just realized that. 👍

**Comment by tak-dev** [comment]
`if (currentLine.StartsWith(triggerFPS))
                {
                    CurrentFPS = currentLine.Replace(triggerFPS, "");
                    LineNumFPS = lineCounter;

                    //set IsFPSUnlimittted bool
                    if (CurrentFPS.StartsWith("0"))
                    {
                        IsFPSUnlimittted = true;
                    }
                    else
                    {
                        IsFPSUnlimittted = false;
                    }
                }`

This is all the code that loads the current FPS. It doesn't change the line once it finds `FrameRateLimit=`.

So all good then? @d3nni 

If not, you might just want to completely reset your config if you haven't. As far as I know it only stores options on the first page of the settings so it's not too detrimental.

**Comment by d3nni** [comment]
It's wierd. :-P

So... can u give me any config I can try? I mean, I already had standard one if I'm not wrong.... Didn't changed anything except streched res.

**Comment by tak-dev** [comment]
If you download the GameUserSettings.zip you uploaded for me earlier, it should work correctly as I just tested it. A fresh config should work as well.

**Comment by d3nni** [comment]
![notworking](https://user-images.githubusercontent.com/20851814/66868123-0ab44100-ef9d-11e9-839f-3b00622b2145.png)

Dunno.... Checked, but that config is not working here.... :-(

**Comment by d3nni** [comment]
I checked now... if I change to "FrameRateLimit=160,000000" with " , " it's working correctly and he is showing 160. If I change to a dot then I get this error. lols :-o

**Comment by tak-dev** [comment]
https://tex.stackexchange.com/questions/18673/german-language-use-of-comma-in-numbers

I think this explains it. Since your system language is set to German it must be looking for a comma rather than a period. I'll have to look into how this can be resolved.

Thanks for helping me troubleshoot this!

**Comment by d3nni** [comment]
Ahhh thought that about things like that.... got to know the exact point. And good to know I can use a comma, so I'll look if it does any changes in game if I just use a comma. :-)

Thanks for helping out also.... Nice support, very fast.... Nice tool and keep up your great work! :-)
